### ISSUE TITLE
Feature Request: Set preffered colorscheme automatically

### ISSUE THREAD

**Issue by armoredvortex** [Sookeyy-12/Sookeyy-12.github.io#1]
Pretty annoying to change it back every time you re-visit the website.

Very easy to implement with your current code.
```js
const prefersDark = window.matchMedia("(prefers-color-scheme:dark)").matches; // true
```

**Comment by Sookeyy-12** [comment]
This would be a nice feature. I'll start working on it soon.

**Comment by Sookeyy-12** [comment]
Feature Added :)
